import Head from "next/head";
import Image from "next/image";
import { BsFillCloudMoonFill } from 'react-icons/bs'
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-md">LOGO NAME</h1>
            <ul className="flex items-center">
              <li><BsFillCloudMoonFill className="cursor-pointer text-2xl"/></li>
              <li>
                <a className="bg-gradient-to-r from- bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">NEAT STUFF</a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
